# Generated by Django 6.0.3 on 2026-04-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YahooFinanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('dividends', models.FloatField()),
                ('stock_splits', models.FloatField()),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Yahoo Finance Data',
                'ordering': ['date'],
            },
        ),
    ]
